services:
  - type: web
    name: premiumwash-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: premiumwash-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://premiumwash:Prishtina.001@cluster0.4oscedz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: premiumwash_secure_jwt_secret_key_2024_enissh_carwash
      - key: ADMIN_EMAIL
        value: enisshabani71@gmail.com  
      - key: ADMIN_PASSWORD
        value: admin123